# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('define', models.TextField()),
                ('threat', models.CharField(choices=[('YES', 'Threatening'), ('NO', 'Non-Threatening')], default='Select', max_length=3)),
            ],
        ),
    ]
