# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issue',
            table='Issue',
        ),
    ]
