# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0002_auto_20170209_1629'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issue',
            table=None,
        ),
    ]
